version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build"
      include: "scope"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/cmd/neblictl"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/cmd/kafka-sampler"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/dist/kafka-sampler"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/dist/otelcol"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build"
      include: "scope"
