site_name: Documentation
copyright: Copyright &copy; 2024 - Neblic
docs_dir: content
strict: true
nav:
    - 'What is Neblic': index.md
    - 'Use cases':
      - 'Event-driven applications': 'use-cases/event-driven.md'
      - 'Real-time data streaming': 'use-cases/real-time-data-streaming.md'
      - 'API monitoring': 'use-cases/api-monitoring.md'
    - 'Quickstart':
      - 'How does Neblic work': 'quickstart/how-does-neblic-work.md'
    # - 'Playground ': 'quickstart/playground.md'
    - 'Getting started': 
      - 'Concepts': 'getting-started/concepts.md'
      - 'Usage': 'getting-started/usage.md'
    - 'Learn':
      - 'Data collection': 'learn/data-collection.md'
      - 'Samplers': 'learn/samplers.md'
      - 'Collector': 'learn/collector.md'
      - 'Storage': 'learn/storage.md'
      - 'Protocol': 'learn/protocol.md'
    - 'How-to guides':
      - 'Get data from Go services': 'how-to/data-from-go-svc.md'
      - 'Get data from Java services': 'how-to/data-from-java-svc.md'
      - 'Get data from other services': 'how-to/data-from-other-svc.md'
      - 'Get data from Apache Kafka': 'how-to/data-from-kafka.md'
      - 'Configure Samplers using neblictl': 'how-to/configure-samplers-using-neblictl.md'
      - 'Store and visualize data with Loki': 'how-to/store-and-visualize-data-with-loki.md'
      - 'Store and visualize metrics with Prometheus': 'how-to/store-and-visualize-metrics-with-prometheus.md'
      - 'Build your own collector': 'how-to/build-your-own-collector.md'
    - 'Reference':
      - 'Rules': 'reference/rules.md'
      - 'Collector': 'reference/collector.md'
      - 'Neblictl': 'reference/neblictl.md'
      - 'Kafka Sampler': 'reference/kafka-sampler.md'
      - 'Go Sampler': https://pkg.go.dev/github.com/neblic/platform/sampler
      - 'Benchmarks': 'reference/benchmarks.md'
theme: 
  name: material
  custom_dir: overrides
  logo: assets/neblic-logo-white.png
  favicon: assets/neblic-favicon.png
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.footer
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/neblic
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/neblic/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/neblic-data
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/neblichq
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@NeblicHQ
  version:
    provider: mike
extra_css:
  - assets/extra.css
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          markdown_extensions:
plugins:
  - glightbox
  - include-markdown
