name: Check documentation links
on:
  workflow_call:

jobs:
  checklinks:
    name: Check documentation links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          architecture: x64
          cache: 'pip'
          cache-dependency-path: 'docs/requirements.txt'

      - name: Install Python dependencies
        run: python3 -m pip install -r ./docs/requirements.txt

      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Generate next docs version
        run: |
          mike deploy --config-file docs/mkdocs.yaml next

      - name: Serve documentation
        run: |
          mike serve --config-file docs/mkdocs.yaml &

      - name: Build sites list
        run: |
          SITES_FILE=${RUNNER_TEMP}/sites
          curl http://localhost:8000/versions.json | jq -r '"http://localhost:8000/"+(.[].version)' > ${SITES_FILE}

          echo "file=${SITES_FILE}" >> $GITHUB_OUTPUT
        id: sites_list

      - name: Run linkcheck
        run :
          cd ${RUNNER_TEMP} &&
            wget https://github.com/filiph/linkcheck/releases/download/3.0.0/linkcheck-3.0.0-linux-x64.tar.gz &&
            tar xvzf linkcheck-3.0.0-linux-x64.tar.gz &&
            ./linkcheck/linkcheck -e --skip-file ${GITHUB_WORKSPACE}/.github/linkchecker/skip -i ${{ steps.sites_list.outputs.file }}